### ISSUE TITLE
[ASK] request to get ELK and VM at ELK Workshop (InfoSecWorld 2017)

### ISSUE THREAD

**Issue by rdamri** [PolitoInc/ELK-Hunting#2]
hello i'm research about this topic and I have struggle with this topic. I want to request the slides and VM   ELK Workshop at InfoSecWorld 2017. can you share it to me? please :)

**Comment by mallware** [comment]
Hi thanks for reaching out. Can you let me know your email address to send you the slides? Feel free to contact me via the contact form at https://www.politoinc.com/ if you don't want to publicly post your email. 

The VM is really outdated at this point, so instead of providing that I recommend you check out the HELK project: https://github.com/Cyb3rWard0g/HELK. It makes it easy to install a modern ELK stack for security analytics. 

If you're in the US, I am also going to be co-teaching an updated version of the Threat Hunting with ELK workshop at 3 upcoming conferences: CarolinaCon, BSides Baltimore, and CircleCityCon (possibly others to follow).

**Comment by rdamri** [comment]
hello thanks for responding to my request. Thanks for the recommendations, it's very valuable to me.
this is my email : amry.darmawikarta@gmail.com

Sadly, I don't reside anywhere near USA-- I'm from SEA, still appreciate the invite, though! Thank you for reaching out!

**Comment by mallware** [comment]
Slides sent to your email!
